export const siteContent = {
  meta: {
    title: 'Carta de aniversario',
  },
  transitions: {
    intro: {
      target: 'letter',
      message: 'Abriendo carta...',
      durationMs: 2800,
    },
    letter: {
      target: 'gift',
      message: 'Abriendo regalo...',
      durationMs: 2600,
    },
    gift: {
      target: 'gallery',
      message: 'Cargando galeria...',
      durationMs: 2400,
    },
  },
  screens: {
    intro: {
      background: 'images/backgrounds/lavender-field.png',
      title: 'Feliz Aniversario <3',
      buttonLabel: '~*~ ABRIR CARTA ~*~',
      topAscii: [
        '        .:*~*:._.:*~*:._.:*~*:.',
        '    .:*~  * <3 * <3 *  ~*:.',
        '.:*~*:._.:*~*:._.:*~*:._.:*~*:.',
      ],
      middleAscii: [
        '    <3<3<3  *  <3<3<3  *  <3<3<3',
        '  *  .:*~*:.  *  .:*~*:.  *',
        '    <3<3<3  *  <3<3<3  *  <3<3<3',
      ],
      bottomAscii: [
        '.:*~*:._.:*~*:._.:*~*:._.:*~*:.',
        '    * <3 * <3 * <3 * <3 *',
        '.:*~*:._.:*~*:._.:*~*:._.:*~*:.',
      ],
    },
    letter: {
      background: 'images/backgrounds/lavender-field.png',
      title: '',
      intro: 'Flor <3,',
      paragraphs: [
        'Quiero que sepas que sos lo mas hermoso que tengo en la vida.',
        'Desde que llegaste a mi vida, todo cambió para bien. El café es más rico, la música suena mejor y absolutamente todo es mas divertido con vos.',
        'No puedo dejar de pensar en vos ni de verte cuando estamos juntos. Sos literalmente mi sol y yo tu girasol.',
        'Estos dos años son apenas un pequeno tramo del camino que tenemos juntos...',
        'por mas viajes, cafecitos, recitales y experiencias juntos <3...',
      ],
      signature: 'Te amo con todo mi ser,<br /><br />Juani <3',
      buttonLabel: '*** ABRIR REGALO ***',
      topAscii: [
        '*~*~*  <3  *~*~*  <3  *~*~*',
        '  .:*~*:. .:*~*:. .:*~*:.',
        '*~*~*  <3  *~*~*  <3  *~*~*',
      ],
      dividerAscii: '<3<3<3 * <3<3<3 * <3<3<3 * <3<3<3',
      bottomAscii: [
        '*~*~*  <3  *~*~*  <3  *~*~*',
        '  .:*~*:. .:*~*:. .:*~*:.',
      ],
    },
    gift: {
      title: '*** TU REGALO ***',
      heading: '>>> Espero que mañana estes lista para <<<',
      festivalImage: 'images/gift/festival.jpg',
      notes: ['Ahora una pequeña galería con algunas fotos que resumen estos dos años juntos.'],
      buttonLabel: '.:*~*:. VER GALERIA .:*~*:.',
      topAscii: [
        '=======================================',
        '  * <3 * <3 REGALO ESPECIAL <3 * <3 *',
        '=======================================',
      ],
      dividerAscii: '<3 * <3 * <3 * <3 * <3 * <3 * <3 * <3',
      bottomAscii: [
        '=======================================',
        '  *~*~*  <3  *~*~*  <3  *~*~*',
        '=======================================',
      ],
    },
    gallery: {
      background: 'images/backgrounds/lavender-field.png',
      title: '.:*~*:. GALERIA .:*~*:.',
      description: '<3 * Por más momentos juntos  * <3',
      topAscii: [
        '==========================================================',
        '  *~*~*  <3  GALERIA DE MOMENTOS  <3  *~*~*',
        '==========================================================',
      ],
      bottomAscii: [
        '<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3',
        '*  Espero que hayas disfrutado este pequeno detalle  *',
        '<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3',
      ],
      images: [
        { src: 'images/gallery/1.jpg', alt: 'Foto 1', label: '1.jpg' },
        { src: 'images/gallery/2.jpg', alt: 'Foto 2', label: '2.jpg' },
        { src: 'images/gallery/3.jpg', alt: 'Foto 3', label: '3.jpg' },
        { src: 'images/gallery/4.jpg', alt: 'Foto 4', label: '4.jpg' },
        { src: 'images/gallery/5.jpg', alt: 'Foto 5', label: '5.jpg' },
        { src: 'images/gallery/6.jpg', alt: 'Foto 6', label: '6.jpg' },
        { src: 'images/gallery/7.jpg', alt: 'Foto 7', label: '7.jpg' },
        { src: 'images/gallery/8.jpg', alt: 'Foto 8', label: '8.jpg' },
        { src: 'images/gallery/9.jpg', alt: 'Foto 9', label: '9.jpg' },
        { src: 'images/gallery/10.jpg', alt: 'Foto 10', label: '10.jpg' },
        { src: 'images/gallery/11.jpg', alt: 'Foto 11', label: '11.jpg' },
        { src: 'images/gallery/12.jpg', alt: 'Foto 12', label: '12.jpg' },
        { src: 'images/gallery/13.jpg', alt: 'Foto 13', label: '13.jpg' },
        { src: 'images/gallery/14.jpg', alt: 'Foto 14', label: '14.jpg' },
        { src: 'images/gallery/15.jpg', alt: 'Foto 15', label: '15.jpg' },
        { src: 'images/gallery/16.jpg', alt: 'Foto 16', label: '16.jpg' },
        { src: 'images/gallery/17.jpg', alt: 'Foto 17', label: '17.jpg' },
      ],
    },
  },
}
